dist: xenial
language: python
python: '3.7'
sudo: false
install:
  - pip install pytest
  - pip install -r requirements.txt
script:
  - make
  - mv dist/lambda.zip dist/latest.zip
  - cp dist/latest.zip dist/$TRAVIS_COMMIT.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: qtechservers
    local-dir: dist
    upload-dir: deployments/lambdas/travis_build/serverProvision
    acl: private
    skip_cleanup: true
    on:
      repo: wahle/MineOnDemand
      all_branches: true
  - provider: lambda
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: "us-east-1"
    function_name: "MineTest"
    role: "arn:aws:iam::140945897298:role/TesterRole"
    module_name: "serverProvisioner"
    handler_name: "lambda_handler"
    runtime: "python3.7"
    timeout: "300"
    zip: "dist/latest.zip"
    skip_cleanup: true
    on:
      repo: wahle/MineOnDemand
      all_branches: true

